spring:
  datasource:
    url: jdbc:mysql://localhost:3306/askfood?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 10000

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#      javax:
#        persistence:
#          schema-generation:
#            scripts:
#              action: create
#              create-target: src/main/resources/ddl.sql

  flyway:
    locations: classpath:db/migration, classpath:db/testdata

  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: ${SENDGRID_APIKEY}

askfood:
  storage:
    type: local
    local:
      photo-directory: /home/calebe/Imagens/catalog
    s3:
      id-access-key: ${S3_ID_ACCESS_KEY}
      secret-access-key: ${S3_SECRET_ACCESS_KEY}
      bucket: askfood-test
      region: us-east-1
      photo-directory: catalog

  email:
    sender: do-not-reply@askfood.com
    impl: fake